_commit: v1.5.1-3-g41eb057
_src_path: /Users/simonjasansky/programming/substrate
author_email: simon@superlinear.eu
author_name: Simon Jasansky
documentation_tool: true
project_description: Test Substrate
project_name: Test Substrate
project_type: app
project_url: https://github.com/SimonJasansky/test_substrate
python_version: '3.10'
typing: optional
with_conventional_commits: true
with_fastapi_api: false
with_typer_cli: false
