_commit: v1.5.1-21-g7133f12
_src_path: /Users/simonjasansky/programming/substrate
author_email: simon@superlinear.eu
author_name: Simon Jasansky
project_description: Test Substrate
project_name: Test Substrate
project_type: package
project_url: https://github.com/SimonJasansky/test_substrate
python_version: '3.10'
typing: optional
with_conventional_commits: true
with_typer_cli: false
