site_name: Test Substrate
site_description: Test Substrate
site_url: https://github.com/SimonJasansky/test_substrate
repo_url: https://github.com/SimonJasansky/test_substrate
repo_name: SimonJasansky/test_substrate

theme:
  name: material

nav:
  - Home: index.md
  - API Reference: reference/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
