name: Documentation

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        
      - name: Set up Python
        run: uv python install 3.10
        
      - name: Install dependencies
        run: uv sync --group dev
        
      - name: Deploy docs with MkDocs
        run: uv run mkdocs gh-deploy --force
